= Abstract (version 25min)

== Abstract

=== FR

Dans le cadre de la bibliothèque de composants Web sur laquelle je travaille, nous avons d'abord publié un paquet sur npm.
Ce choix impose aux utilisateurs de nos composants de parcourir la jungle des outils basés sur Node.js, avec ses "npm install bidule", ses "babel truc" et autres "webpack machin".
La période où il suffisait juste d'ajouter une balise script à la main qui pointe vers un CDN est loin derrière nous.

Afin de faciliter l'usage de nos composants, nous avons créé un "smart CDN" pour exposer nos composants.
Au menu de cette session, je vous propose de voir comment nous avons mis en place ce système.
Nous expliquerons comment nous construisons les fichiers et comment nous les exposons.
Ça sera l'occasion d'analyser les enjeux de performance et mesurer concrètement les impacts de différentes techniques d'optimisation.

=== EN

== Message pour le comité

=== FR

=== EN

== Idées de titre

* Mise en place d'un smart CDN pour distribuer des Web Components

=== Autres
